name: Build and Release Compose Desktop App

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_pattern: '*.deb'
            search_path: 'build/compose/binaries/main/deb'
            gradle_task: 'packageDeb'
          - os: windows-latest
            artifact_pattern: '*.msi'
            search_path: 'build/compose/binaries/main/msi'
            gradle_task: 'packageMsi'
          - os: macos-latest
            artifact_pattern: '*.app'
            search_path: 'build/compose/binaries/main/app'
            gradle_task: 'packageDmg'
            archive_name: 'PortMapper-macOS.zip'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle wrapper (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build package
        run: ./gradlew ${{ matrix.gradle_task }}

      - name: Prepare macOS artifact
        if: matrix.os == 'macos-latest'
        run: |
          cd ${{ matrix.search_path }}
          zip -r ${{ matrix.archive_name }} *.app
          echo "artifact_path=${{ matrix.search_path }}/${{ matrix.archive_name }}" >> $GITHUB_OUTPUT
          echo "artifact_name=${{ matrix.archive_name }}" >> $GITHUB_OUTPUT

      - name: Find Linux/Windows artifacts
        if: matrix.os != 'macos-latest'
        id: find-artifacts
        run: |
          artifact_path=$(find "${{ matrix.search_path }}" -type f -name "${{ matrix.artifact_pattern }}" | head -n 1)
          if [ -z "$artifact_path" ]; then
            echo "::error::No artifact found for pattern ${{ matrix.artifact_pattern }} in ${{ matrix.search_path }}"
            ls -la "${{ matrix.search_path }}" || true
            exit 1
          fi
          echo "artifact_path=$artifact_path" >> $GITHUB_OUTPUT
          echo "artifact_name=$(basename "$artifact_path")" >> $GITHUB_OUTPUT

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: PortMapper ${{ github.ref_name }}
          body: |
            Auto-generated release for PortMapper version ${{ github.ref_name }}
            Built for ${{ matrix.os }}
          files: ${{ steps.find-artifacts.outputs.artifact_path || steps.prepare-macos.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}