name: Build and Release Compose Desktop App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_pattern: '*.deb'
            artifact_name: 'PortMapper-Linux.deb'
          - os: windows-latest
            artifact_pattern: '*.msi'
            artifact_name: 'PortMapper-Windows.msi'
          - os: macos-latest
            artifact_pattern: '*.app'
            artifact_name: 'PortMapper-macOS.zip'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle wrapper
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build package
        run: ./gradlew createDistributable

      - name: Prepare artifact
        id: prepare-artifact
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            cd build/compose/binaries/main/app
            zip -r ${{ matrix.artifact_name }} *.app
            echo "artifact_path=build/compose/binaries/main/app/${{ matrix.artifact_name }}" >> $GITHUB_OUTPUT
          else
            artifact_path=$(find build/compose/binaries -type f -name "${{ matrix.artifact_pattern }}" | head -n 1)
            cp "$artifact_path" "${{ matrix.artifact_name }}"
            echo "artifact_path=${{ matrix.artifact_name }}" >> $GITHUB_OUTPUT
          fi
          echo "artifact_name=${{ matrix.artifact_name }}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ steps.prepare-artifact.outputs.artifact_path }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded artifacts
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: PortMapper ${{ github.ref_name }}
          body: |
            Multi-platform release for PortMapper version ${{ github.ref_name }}
            Contains installers for Windows, macOS and Linux
          files: |
            artifacts/PortMapper-Windows.msi
            artifacts/PortMapper-Linux.deb
            artifacts/PortMapper-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}